# This workflow will install Python dependencies, run tests with a single version of Python

name: Linting

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12.3
      uses: actions/setup-python@v3
      with:
        python-version: "3.12.3"
    - name: Install dependencies and the package
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install .
    - name: Run the linter
      run: |
        pylint --rcfile=pylintrc src tests